### ISSUE TITLE
Not able to send metrics from React/Nextjs application

### ISSUE THREAD

**Issue by chethan-devopsnow** [cabify/prom-react#104]
Hello, I am new to this concept and I am not sure if I am doing it right.

Objective: We are using Victoria metrics as engine. In order to send metrics data I followed your readme file. I am getting the following error 

`cannot decompress request with length 0: snappy: corrupt input `

Published:
@cabify/prom-react@0.2.1-beta.0

Payload:  I see every metrics value as 0
`
# HELP prom_react_app_loaded Application loaded counter
# TYPE prom_react_app_loaded counter
prom_react_app_loaded{app_name="demo-ui",owner="demo",status="success"} 1
# HELP prom_react_app_unloaded Application unloaded counter
# TYPE prom_react_app_unloaded counter
# HELP prom_react_navigation_duration_seconds Total navigation duration between pages in seconds
# TYPE prom_react_navigation_duration_seconds histogram
prom_react_navigation_duration_seconds_count 0
prom_react_navigation_duration_seconds_sum 0
prom_react_navigation_duration_seconds_bucket{le="1"} 0
prom_react_navigation_duration_seconds_bucket{le="2"} 0
prom_react_navigation_duration_seconds_bucket{le="3"} 0
prom_react_navigation_duration_seconds_bucket{le="4"} 0
prom_react_navigation_duration_seconds_bucket{le="5"} 0
prom_react_navigation_duration_seconds_bucket{le="7"} 0
prom_react_navigation_duration_seconds_bucket{le="10"} 0
prom_react_navigation_duration_seconds_bucket{le="15"} 0
prom_react_navigation_duration_seconds_bucket{le="+Inf"} 0
prom_react_navigation_duration_seconds_bucket{le="0.01"} 0
prom_react_navigation_duration_seconds_bucket{le="0.1"} 0
# HELP prom_react_ttc_seconds Section time to interactive in seconds
# TYPE prom_react_ttc_seconds histogram
prom_react_ttc_seconds_count 0
prom_react_ttc_seconds_sum 0
prom_react_ttc_seconds_bucket{le="1"} 0
prom_react_ttc_seconds_bucket{le="2"} 0
prom_react_ttc_seconds_bucket{le="3"} 0
prom_react_ttc_seconds_bucket{le="4"} 0
prom_react_ttc_seconds_bucket{le="5"} 0
prom_react_ttc_seconds_bucket{le="7"} 0
prom_react_ttc_seconds_bucket{le="10"} 0
prom_react_ttc_seconds_bucket{le="15"} 0
prom_react_ttc_seconds_bucket{le="+Inf"} 0
prom_react_ttc_seconds_bucket{le="0.01"} 0
prom_react_ttc_seconds_bucket{le="0.1"} 0
# HELP prom_react_ttu_seconds Section time to usable in seconds
# TYPE prom_react_ttu_seconds histogram
prom_react_ttu_seconds_count 0
prom_react_ttu_seconds_sum 0
prom_react_ttu_seconds_bucket{le="1"} 0
prom_react_ttu_seconds_bucket{le="2"} 0
prom_react_ttu_seconds_bucket{le="3"} 0
prom_react_ttu_seconds_bucket{le="4"} 0
prom_react_ttu_seconds_bucket{le="5"} 0
prom_react_ttu_seconds_bucket{le="7"} 0
prom_react_ttu_seconds_bucket{le="10"} 0
prom_react_ttu_seconds_bucket{le="15"} 0
prom_react_ttu_seconds_bucket{le="+Inf"} 0
prom_react_ttu_seconds_bucket{le="0.01"} 0
prom_react_ttu_seconds_bucket{le="0.1"} 0
# HELP prom_react_performance_seconds Application performance load time in seconds
# TYPE prom_react_performance_seconds histogram
prom_react_performance_seconds_count 0
prom_react_performance_seconds_sum 0
prom_react_performance_seconds_bucket{le="1"} 0
prom_react_performance_seconds_bucket{le="2"} 0
prom_react_performance_seconds_bucket{le="3"} 0
prom_react_performance_seconds_bucket{le="4"} 0
prom_react_performance_seconds_bucket{le="5"} 0
prom_react_performance_seconds_bucket{le="7"} 0
prom_react_performance_seconds_bucket{le="10"} 0
prom_react_performance_seconds_bucket{le="15"} 0
prom_react_performance_seconds_bucket{le="+Inf"} 0
prom_react_performance_seconds_bucket{le="0.01"} 0
prom_react_performance_seconds_bucket{le="0.1"} 0
`

**Comment by alejandrofdiaz** [comment]
I'm sorry for the late response, does this error persist?
