### ISSUE TITLE
Custom metrics being recreated each time browser reloads

### ISSUE THREAD

**Issue by diogomoreira** [cabify/prom-react#163]
I'm trying to do an example using custom metrics precisely as the documentation points out. So, I'm defining my custom metric

```
const customMetrics: MetricDefinition[] = [
  {
    type: 'counter',
    name: 'my_app_report_download_count',
    description: 'Number of reports downloaded',
  },
];
root.render(
  <MetricsProvider
    appName="myApp"
    metricsAggregatorUrl="http://localhost:9091/metrics/job/download"
    customMetrics={customMetrics}
  >
    <MetricsDebugOverlay withLogger={true} />
    <App />
  </MetricsProvider>
);
```

And it is triggering an observation using a button action.

```

function App() {
  const { observe } = useMetrics();

  const downloadReport = () => {
    observe("my_app_report_download_count", { custom_tag: "download" }, 1);
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <button onClick={downloadReport}>Enviar métrica</button>
      </header>
    </div>
  );
}
```
But every time I refresh my app `Ctrl/⌘-R`, the metric is being created again and the previous value is being lost. From what I saw in the code (`src/createMetrics.ts`), it checks if the Golden Metrics are already created to avoid losing previous values. Shouldn't this be also done to the custom metrics? 

So, **Is this how the custom metrics are supposed to work? Resetting values every time the app refreshes? Or am I doing something wrong?**

**Comment by alexgallardo** [comment]
Hi Diogo!

Yes, it is expected that all values are reset when reloading an app, for custom or default metrics. Those values are expected to persist in a Prometheus db, not the browser. Metric values only persist in the browser while waiting to successfully send them. After sending them, the values are reset.

It seems you were testing the package without setting an aggregation service and the counter metric you created got their values added together indefinitely between every full page reload.

I hope that answer your question.

**Comment by diogomoreira** [comment]
Hi @alexgallardo, thanks for the response.

I'm using an aggregator service (Prometheus Gateway) to test the package. I was just trying to understand the usage flow. Thanks for the clarification! It helped me a lot
