### ISSUE TITLE
Error building with @cabify/prom-react

### ISSUE THREAD

**Issue by aggaton** [cabify/prom-react#43]
Getting the following error when trying to build

./node_modules/@shopify/react-performance/build/esm/performance-report.mjs
Can't import the named export 'Header' from non EcmaScript module (only default export is available)

**Comment by JotiKaushal** [comment]
> Getting the following error when trying to build
> 
> ./node_modules/@shopify/react-performance/build/esm/performance-report.mjs Can't import the named export 'Header' from non EcmaScript module (only default export is available)

I am also getting the same error.

Any update on this?

**Comment by alejandrofdiaz** [comment]
We're investigating this.
Can you please provide further information?
 - Are you building a project with `@cabify/prom-react` or are you trying to build `@cabify/prom-react`
 - What node version are you running when building.
 - Does your configuration supports dealing with `.mjs` [as this issue suggests](https://github.com/polkadot-js/extension/issues/621#issuecomment-759341776)?

I've tried both either building `@cabify/prom-react` and building a CRA project with that dependency and it seems to work correctly.
